model:
  name: microsoft/deberta-v3-base

data:
  train_path: data/processed/extractive_qa_trigger/train.jsonl
  val_path: data/processed/extractive_qa_trigger/val.jsonl
  test_path: data/processed/extractive_qa_trigger/test.jsonl

training:
  output_dir: outputs/models/extractive_qa_trigger
  output_dir_final: outputs/models/extractive_qa_trigger/final

  num_train_epochs: 2
  learning_rate: 0.00003
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  weight_decay: 0.01

  max_length: 384
  doc_stride: 128
  max_answer_length: 30