model:
  name: deepset/roberta-base-squad2

data:
  train_path: data/processed/extractive_qa_main_arguments/train.jsonl
  val_path: data/processed/extractive_qa_main_arguments/val.jsonl
  test_path: data/processed/extractive_qa_main_arguments/test.jsonl

raw_data:
  train_path: data/raw/train_main.json
  val_path: data/raw/val_main.json
  test_path: data/raw/test_main.json

trigger_predictions:
  train_path: outputs/predictions/extractive_qa_trigger_train.jsonl
  val_path: outputs/predictions/extractive_qa_trigger_val.jsonl
  test_path: outputs/predictions/extractive_qa_trigger_test.jsonl

training:
  output_dir: outputs/models/extractive_qa_main_arguments
  output_dir_final: outputs/models/extractive_qa_main_arguments/final

  num_train_epochs: 3
  learning_rate: 0.00002
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  weight_decay: 0.01

  max_length: 384
  doc_stride: 128
  max_answer_length: 60

prediction:
  n_best_size: 50
  max_spans_per_argument: 1
  null_score_diff_threshold: 0.0